### ISSUE TITLE
ACE bug

### ISSUE THREAD

**Issue by VictorMcGalrish** [sw4l/15thsoc#108]
Task Force Alpha

I'm reporting a bug (well two) occurring in FTX 06-15. At two time I have end up having a glitch after an ACE interaction.

The first one was after been shot down, my corpsman drag me to a bunker and drop me inside. When he drop me I have gone under the ground and end up on a hill underground. I was forced to respawn.

The second one was while I was trying to carry my corpsman. He might have die while in the process of taking him on my shoulder. His body made a weird move while the animation was going on and when the animation end up, I was stuck unable to move or do anything except changing my radio net. I was stuck moving slowly toward the beach standing. I was unstuck after someone handcuffed me and bandage me (since I've been hit while glitched) and free me.

If you need more information, feel free to contact me.

Sgt H. Mitchell
Fire Team Leader
Gambler 1-2-C

**Comment by MrPiipe** [comment]
There's nothing we can do, this are ACE 3 bugs or just ArmA bugs. 
1. ArmA bug, when he set you down there was a collision between you and the bunker and it placed you under ground, common bug from ArmA. Nothing we can do about it.
2. ACE 3 bug, you can try and solve this going to Esc -> Ace 3 options -> Fix Headbug. Animation bug, when your buddy died you got stuck in the animation and it didn't come back. Report it to the ACE 3 github here: https://github.com/acemod/ACE3/issues (This bug has been there since ACE 2).

Sadly, nothing we can do on our end. Therefore I'm closing this.
