### ISSUE TITLE
UH-1Y Misc

### ISSUE THREAD

**Issue by DivineWind04** [sw4l/15thsoc#89]
*I appreciate the work on the formation lights, is it possible however to make the beacon light more visible during the day time?
*Is the HUD fixable so that it centers with the projectile?
*Can we get some GAU-21s?!
*Any chance we can import better sounds for the UH-1

SNA D. Nguyen
Gunfighter 1-1 CP
HMLA-369 UH-1Y

**Comment by Karneck** [comment]
Formation Lights are not meant to be used in the daytime... It's for night time flying only... 
Please do your homework before asking a question like this.

No idea what the heck this even means.

That's something you should ask your CoC.

Go find some and I'll put them in.

**Comment by DivineWind04** [comment]
Sorry the formation lights were a separate thing with the beacon. The beacon/anti collision lights aren't visible in the day when they should be.

After this big mod, the drop down HUD from the UH-1 was gone, is it possible to put it back but have it centered instead of not being accurate from the old one?

They'd love to. 

Not sure how sounds work in Arma, are they any chance like the microsoft flight simulator platform where there are .wav and a configuration file?

**Comment by Karneck** [comment]
Send it up your CoC as a request. It's up to them to decide if they want them brighter or not, at the time I showed it. They said it was fine.

Ask your CoC if they want it back. I removed it because I didn't feel like spending hours trying to center the sighting.

Actually, they didn't when I asked them. Please try again and direct such comments to them instead of speaking for them.

Sound bites are sound bites, but the config coding is vastly deeper then just throwing a sound bit in.

**Comment by Karneck** [comment]
No further comment from creator. Apparently asking his CoC is too hard. Closing.

**Comment by DivineWind04** [comment]
Please don't assume, I asked and like you said, my CoC said it's not needed at this time.
