### ISSUE TITLE
Poor Poor AAV

### ISSUE THREAD

**Issue by Karneck** [sw4l/15thsoc#94]
Working with CUP. Should be able to get our poor friend here updated.

**Comment by MrPiipe** [comment]
Any updates on this Schultz? Got some complaints about the Gator being very twitchy and a hassle to drive.
Else, could we modify it a bit and make it better? Could it be the new water drive causing this issues?

**Comment by Francis-Velten** [comment]
Issues Gator is having with the current model as of 04DEC15:

-[]  Vehicle control on land is extremely twitchy, which is exacerbated with increasing speed.  A single keypress to adjust to the left or the right introduces a very large result which results in a driver-induced oscillation. It basically becomes uncontrollable over 35 km/h unless you are going in a straight line and using the mouse to keep it on the roadway.

-[]  Previously I had put to the gator team that a very small correction in the yaw axis would be more precise for turning while the amphibious drive was engaged.  I did not anticipate that this would cause the amount of time needed to make a turn of more than a few degrees to take the large amount of time that it does.  Is it possible to speed up the key-repeat rate somehow so that the small turns go faster we need to more that a slight heading adjustment?

-[]  Smoke Grenade canisters are often empty when we get into the vehicles at the beginning of an operation, FTX, or training.  I have been unable to figure out why this is.  If the vehicle is moved to a repair/rearm facility, the smoke grenade canisters are reloaded.  This issue has happened during the last deployment and into the FTX cycle.

-[] The Gator vehicles are, in our experience, more often than not unable to be spawned in or manipulated via Zeus.  When this issue is present, the vehicle does not even appear in the list of assets available is Zeus.  When it is not, it is the first vehicle in NATO > Armored.  This often causes issues for us and other sections of the unit when we are attempting to perform a join training.

-[]  Commander position is, IRL, not used by the VC, who normally is in the Up-Gunned Weapon System.  It is utilized by the ranking member of the embarked infantry.  This position has the control for the smoke grenade launchers.  We would like to have that moved to the "gunner" position.

-[]  Driver is unable to turn out if the troop commander's (right now marked as vehicle commander's position) is unoccupied 

-[] FFV is no longer implemented to allow either crew or infantry in the rear of the vehicle to stand through open hatches and fire out. If we get this back we would prefer it if the vision point for anyone in a FFV position was high enough for that/those marines to easily see/aim/shoot far enough down in order to engage danger-close enemies.

-[] Corollary to the above:  IRL the top hatches of the AAV are removable (including the center post) and it would greatly improve the vision of crew/passengers who are turned out to the sides of the vehicle.  (It is my understanding that this is not normally done during an amphibious operation as it could compromise the buoyancy of the vehicle)

-[]  Texture issue topside of the front of the hull is has a texture issue from interior views.  If you were to turn out as the driver , the hull around you appears grey.  This is not evident from 3rd-person view, only from 1st-person.

-[] From time to time, Gator includes in its ranks former IRL 1833's and 2141's, who have informed us that IRL, the UGWS has firing lockouts to prevent the weapons system from firing over/through positions of the vehicle that could potentially be manned and turned out of.  While I don't feel this is 100% necessary (and may be difficult or impossible to implement in game within reason), I am including this in the interests of realism.

Feature requests:

-[] Smoke generation system like the one on Burne's M1A1, controlled by the driver.  This is regularly used by the AAV crews IRL to generate smoke screens during an amphibious assault.  This should be a toggle, not needing a crew member to hold down a key to keep the smoke jenny in operation.

-[] In Arma 2: OA with ACE 2, Gator was able to adjust the amount of ammunition in the vehicle by adding additional ammo to the vehicle's inventory.  We would like to see if it is possible for this to happen again.

-[] Again, with ACE 2, Gator was able to utilize range cards and adjust the traverse and elevation of the UGWS manually, making indirect fires with the Mk19  much more accurate than we are able to do at this time.

**Comment by Fight9** [comment]
These issues arose after the recent update I'm guessing? 

I'm afraid most of your requests will go unanswered. When ever we repack the mod, the vehicle no longer floats. I've had to resort to fixing through inheritance, which severely limits what I am able to do. 

As for the sea drive causing issues, I would say highly doubtful. The script completely exits if the vehicle is on land. I'll take a look at it, but who knows. I can make simple config changes too, so I'll take a look at the suspension to see if any changes have been made in vanilla Arma there. Might solve driving issues. 

Schultz was looking into a CUP ported version but I have not heard anything since. That's probably our best options unless RHS has a version. 

Hope for the best - prepare for the worst, I'd say.

**Comment by MrPiipe** [comment]
These issues were from before the update. Most of them have been there a long time I believe. Gator was just waiting for Burnes to hopefully fix them.

**Comment by MrPiipe** [comment]
https://bitbucket.org/15mod/15mod/issues/8/aav-issues
